import { useEffect, useState } from 'react';
import type { Grumble, Preferences } from './types';
import { requestGrumble } from './lib/api';
import { defaults, loadLocal, saveLocal } from './lib/storage';
import { supabase } from './lib/supabase';
import { AuthPanel } from './components/AuthPanel';
import { Settings } from './components/Settings';
function speak(text: string) { speechSynthesis.cancel(); speechSynthesis.speak(new SpeechSynthesisUtterance(text)); }
export default function App() {
 const initial=loadLocal(),[history,setHistory]=useState<Grumble[]>(initial.history),[preferences,setPreferences]=useState<Preferences>(initial.preferences??defaults),[current,setCurrent]=useState<Grumble|null>(initial.history[0]??null),[prompt,setPrompt]=useState(''),[loading,setLoading]=useState(false),[authOpen,setAuthOpen]=useState(false),[email,setEmail]=useState<string|null>(null);
 useEffect(()=>{saveLocal({history,preferences});},[history,preferences]); useEffect(()=>{if(!supabase)return;supabase.auth.getUser().then(({data})=>setEmail(data.user?.email??null));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setEmail(s?.user.email??null));return()=>subscription.unsubscribe();},[]);
 async function generate(){setLoading(true);const result=await requestGrumble(preferences.tone,prompt.trim()||undefined);setCurrent(result);setHistory(p=>[result,...p].slice(0,30));setPrompt('');setLoading(false);if(preferences.autoplay)speak(result.text)}
 function toggleFavorite(id:string){setHistory(p=>p.map(x=>x.id===id?{...x,favorite:!x.favorite}:x));setCurrent(p=>p?.id===id?{...p,favorite:!p.favorite}:p)}
 return <main className={preferences.reducedMotion?'reduce-motion':''}><header><a className="brand" href="/">GRUMPY <i>GUY</i>AI</a><div><span className="user">{email??'Private mode'}</span><button className="text-button" onClick={()=>email?supabase?.auth.signOut():setAuthOpen(true)}>{email?'Sign out':'Sign in'}</button></div></header><section className="hero"><p className="eyebrow">YOUR DISAGREEABLE COPILOT</p><h1>Motivation, <em>with complaints.</em></h1><p className="lede">Ask for a reality check, or press the button and let him mutter.</p><div className="composer"><input value={prompt} maxLength={500} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>e.key==='Enter'&&!loading&&generate()} aria-label="Optional context" placeholder="What are you avoiding?"/><button className="primary" onClick={generate} disabled={loading}>{loading?'Grumbling…':'Make him grumble'}</button></div></section><section className="stage" aria-live="polite"><div className="face" aria-hidden="true">ಠ_ಠ</div><div className="speech">{current?<><p className="quote">“{current.text}”</p><div className="actions"><span>{current.tone} · {new Date(current.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><button className="icon" onClick={()=>speak(current.text)} aria-label="Read aloud">◖</button><button className="icon" onClick={()=>toggleFavorite(current.id)} aria-label="Favorite">{current.favorite?'★':'☆'}</button></div></>:<p className="quote empty">No opinion yet. A rare moment of peace.</p>}</div></section><div className="lower"><section className="history"><p className="eyebrow">RECENT DAMAGE</p><h2>Grumble log</h2>{history.length?<ul>{history.slice(0,6).map(item=><li key={item.id}><button onClick={()=>setCurrent(item)}><span>{item.text}</span><small>{item.favorite?'★ ':''}{item.tone}</small></button></li>)}</ul>:<p className="muted">Your glorious procrastination record will appear here.</p>}</section><Settings preferences={preferences} onChange={setPreferences} onClear={()=>{setHistory([]);setCurrent(null)}}/></div><footer>Built for people who ship anyway. <button className="text-button" onClick={()=>setAuthOpen(true)}>Back up your data</button></footer>{authOpen&&<AuthPanel onClose={()=>setAuthOpen(false)}/>}</main>;
}
